services:
  - type: web
    name: entrealmohadones-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 10000
